---
# tasks file for web_role
- name: "installing the httpd server"
  package:
          name: "httpd"
          state: present

- name: "installing the php on the webserver"
  package:
          name: "php"
          state: present


- name: "copying the content into webserver"
  copy:
          dest: "/var/www/html/index.php"
          src: "files/index.php"

- name: "starting the httpd"
  service:
          name: "httpd"
          state: restarted
